In [27]:

import warnings
warnings.filterwarnings("ignore")


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import matplotlib.cm as cm
from random import seed,sample,randrange
from sklearn.model_selection import train_test_split,KFold
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score, roc_curve, auc,\
precision_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelBinarizer

In [28]:
# loading data

data = pd.read_csv("wealth.csv")

In [29]:
data.describe()

age        fnlwgt  education.num  capital.gain  capital.loss  \
count  32561.000000  3.256100e+04   32561.000000  32561.000000  32561.000000   
mean      38.581647  1.897784e+05      10.080679   1077.648844     87.303830   
std       13.640433  1.055500e+05       2.572720   7385.292085    402.960219   
min       17.000000  1.228500e+04       1.000000      0.000000      0.000000   
25%       28.000000  1.178270e+05       9.000000      0.000000      0.000000   
50%       37.000000  1.783560e+05      10.000000      0.000000      0.000000   
75%       48.000000  2.370510e+05      12.000000      0.000000      0.000000   
max       90.000000  1.484705e+06      16.000000  99999.000000   4356.000000   

       hours.per.week  
count    32561.000000  
mean        40.437456  
std         12.347429  
min          1.000000  
25%         40.000000  
50%         40.000000  
75%         45.000000  
max         99.000000

In [30]:
data.shape

(32561, 15)

In [31]:
data.head(7)

age workclass  fnlwgt     education  education.num marital.status  \
0   90         ?   77053       HS-grad              9        Widowed   
1   82   Private  132870       HS-grad              9        Widowed   
2   66         ?  186061  Some-college             10        Widowed   
3   54   Private  140359       7th-8th              4       Divorced   
4   41   Private  264663  Some-college             10      Separated   
5   34   Private  216864       HS-grad              9       Divorced   
6   38   Private  150601          10th              6      Separated   

          occupation   relationship   race     sex  capital.gain  \
0                  ?  Not-in-family  White  Female             0   
1    Exec-managerial  Not-in-family  White  Female             0   
2                  ?      Unmarried  Black  Female             0   
3  Machine-op-inspct      Unmarried  White  Female             0   
4     Prof-specialty      Own-child  White  Female             0   
5      Other-service      Unmarried  White  Female             0   
6       Adm-clerical      Unmarried  White    Male             0   

   capital.loss  hours.per.week native.country        income  
0          4356              40  United-States  middle-class  
1          4356              18  United-States  middle-class  
2          4356              40  United-States  middle-class  
3          3900              40  United-States  middle-class  
4          3900              40  United-States  middle-class  
5          3770              45  United-States  middle-class  
6          3770              40  United-States  middle-class

In [32]:

data_new = data.copy() 
nan_value = float("NaN")
data_new.replace("?", nan_value, inplace=True)
data_new.dropna(inplace=True)



In [33]:
data_new.head(7)

age    workclass  fnlwgt     education  education.num marital.status  \
1   82      Private  132870       HS-grad              9        Widowed   
3   54      Private  140359       7th-8th              4       Divorced   
4   41      Private  264663  Some-college             10      Separated   
5   34      Private  216864       HS-grad              9       Divorced   
6   38      Private  150601          10th              6      Separated   
7   74    State-gov   88638     Doctorate             16  Never-married   
8   68  Federal-gov  422013       HS-grad              9       Divorced   

          occupation    relationship   race     sex  capital.gain  \
1    Exec-managerial   Not-in-family  White  Female             0   
3  Machine-op-inspct       Unmarried  White  Female             0   
4     Prof-specialty       Own-child  White  Female             0   
5      Other-service       Unmarried  White  Female             0   
6       Adm-clerical       Unmarried  White    Male             0   
7     Prof-specialty  Other-relative  White  Female             0   
8     Prof-specialty   Not-in-family  White  Female             0   

   capital.loss  hours.per.week native.country        income  
1          4356              18  United-States  middle-class  
3          3900              40  United-States  middle-class  
4          3900              40  United-States  middle-class  
5          3770              45  United-States  middle-class  
6          3770              40  United-States  middle-class  
7          3683              20  United-States    rich-class  
8          3683              40  United-States  middle-class

In [34]:
X = data_new.drop("income",1)
y = data_new.income

In [35]:
X =np.array(pd.get_dummies(X,prefix=['work_','edu_','ststus_','occ_','reltn_','race_','sex_','conty_']))
jobs_encoder = LabelBinarizer()
jobs_encoder.fit(y)
transformed = jobs_encoder.transform(y)
y =np.array(pd.DataFrame(transformed))

In [96]:
RandomState = 42
seed(21)
Accuracy_avg = 0
Precision_avg = 0

In [97]:

""" parametersRF = {'n_estimators':15,'oob_score':True,'class_weight': "balanced",'n_jobs':-1,\
                 'random_state':RandomState}
RF = RandomForestClassifier(**parametersRF)
fitted_vals = RF.fit(X_train, y_train)
 

predictionsRF = RF.predict(X_test)
 
     

CM_RF = confusion_matrix(y_test,predictionsRF)
CR_RF = classification_report(y_test,predictionsRF)
fprRF, recallRF, thresholdsRF = roc_curve(y_test, predictionsRF)
AUC_RF = auc(fprRF, recallRF)

resultsRF = {"Confusion Matrix":CM_RF,"Classification Report":CR_RF,"Area Under Curve":AUC_RF}"""

' parametersRF = {\'n_estimators\':15,\'oob_score\':True,\'class_weight\': "balanced",\'n_jobs\':-1,                 \'random_state\':RandomState}\nRF = RandomForestClassifier(**parametersRF)\nfitted_vals = RF.fit(X_train, y_train)\n \n\npredictionsRF = RF.predict(X_test)\n \n     \n\nCM_RF = confusion_matrix(y_test,predictionsRF)\nCR_RF = classification_report(y_test,predictionsRF)\nfprRF, recallRF, thresholdsRF = roc_curve(y_test, predictionsRF)\nAUC_RF = auc(fprRF, recallRF)\n\nresultsRF = {"Confusion Matrix":CM_RF,"Classification Report":CR_RF,"Area Under Curve":AUC_RF}'

In [101]:
def rf(X_train,y_train,X_test,y_test,i):
    parametersRF = {'n_estimators':15,'oob_score':True,'class_weight': "balanced",'n_jobs':-1,\
                 'random_state':RandomState}
    RF = RandomForestClassifier(**parametersRF)
    fitted_vals = RF.fit(X_train, y_train)
 

    predictionsRF = RF.predict(X_test)
 
     
    

    CM_RF = confusion_matrix(y_test,predictionsRF)
    AC_RF = accuracy_score(y_test,predictionsRF)
    
    PR_RF = precision_score(y_test,predictionsRF)
    
    
    resultsRF = {"Confusion Matrix":CM_RF,"Accuracy":AC_RF,"Precision":PR_RF}
    print("===============>", i ,"Iteration<==================")
    for measure in resultsRF:
        print(measure,": \n",resultsRF[measure])
    return AC_RF,PR_RF

In [102]:
def cross_validation_split(dataset, folds=3):
    dataset_split = list()
    dataset_copy = list(dataset)
    fold_size = int(len(dataset) / folds)
    for i in range(folds):
        fold = list()
        while len(fold) < fold_size:
            index = randrange(len(dataset_copy))
            fold.append(dataset_copy.pop(index))
        dataset_split.append(fold)
    return dataset_split
 

dataset = [[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]]
folds = cross_validation_split(dataset, 5)
dataset =pd.DataFrame([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])

In [104]:
kf = KFold(n_splits=5)
kf.get_n_splits(X)
i=1

for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    Accuracy_avg,Precision_avg=rf(X_train,y_train,X_test,y_test,i)
    i=i+1


===============> 1 Iteration<==================
Confusion Matrix : 
 [[2974  302]
 [1342 1415]]
Accuracy : 
 0.7274987568373943
Precision : 
 0.8241118229470006
===============> 2 Iteration<==================
Confusion Matrix : 
 [[4487  395]
 [ 560  591]]
Accuracy : 
 0.8417039615448367
Precision : 
 0.5993914807302231
===============> 3 Iteration<==================
Confusion Matrix : 
 [[4455  379]
 [ 594  604]]
Accuracy : 
 0.8386936339522546
Precision : 
 0.6144455747711088
===============> 4 Iteration<==================
Confusion Matrix : 
 [[4456  377]
 [ 615  584]]
Accuracy : 
 0.8355437665782494
Precision : 
 0.6077003121748179
===============> 5 Iteration<==================
Confusion Matrix : 
 [[4431  398]
 [ 598  605]]
Accuracy : 
 0.8348806366047745
Precision : 
 0.6031904287138584


In [105]:
print("Accuracy Avg:",Accuracy_avg," Precision Avg:",Precision_avg)

Accuracy Avg: 0.8348806366047745  Precision Avg: 0.6031904287138584
